birthday/birthday/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('birthday_show.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

birthday/birthday_show/urls.py
from django.urls import path
from . import views

app_name = 'birthday_show'

urlpatterns = [
    path('', views.index, name='index'),
] 

birthday/users/urls.py
from django.contrib.auth.views import LogoutView 
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
]

birthday/birthday_show/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime, date


class User(AbstractUser):
    """Модель пользователей."""
    
    dob = models.DateField(
        'date of birthday',
        auto_now_add=False,
        blank=False,
        null=True,
    )

    bio = models.TextField(
        'biography',
        blank=True,
    )

    username = models.CharField(
        'username',
        max_length=150,
        unique=True,
        blank=False,
        null=False
    )
    email = models.EmailField(
        'email',
        max_length=254,
        unique=True,
        blank=False,
        null=False
    )

    confirmation_code = models.CharField(
        'confirmation_code',
        max_length=70,
        unique=True,
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['username']
        verbose_name = 'user'
        verbose_name_plural = 'users'

birthday/users/models.py
from django.db import models

# Create your models here.

birthday/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'})) 
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'dob')
        widgets = {
            'dob': forms.DateInput(attrs={'class': 'datepicker'}),
               }

birthday/birthday_show/views.py
from calendar import HTMLCalendar
from datetime import datetime

from django.shortcuts import render

from .models import User


def index(request):
    page_obj = User.objects.filter(dob__day=datetime.now().date().day, dob__month=datetime.now().date().month)
    template = 'birthday_show/index.html'
    year = int(datetime.now().date().year)
    month = int(datetime.now().date().month)
    now = datetime.now()
    time = now.strftime('%I:%M:%S %p')
    cal = HTMLCalendar().formatmonth(year, month)
    context = {
        'page_obj': page_obj,
        'year': year,
        'month': month,
        'cal': cal,
        'time': time,
    }
    return render(request, template, context)

birthday/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('birthday_show:index')
    template_name = 'users/signup.html' 

birthday/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>    
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="img/fav/fav.ico" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.theme.min.css' %}" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>
  <body>
    <header>
      {% include 'includes/header.html' %}
      {% block header %}{% endblock %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %} 
    </footer>
<script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.12.1/jquery-ui.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>

birthday/templates/birthday_show/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>First Name</th>
        <th>Last Name</th>
      </tr>
    </thead>
    {% for obj in page_obj %}
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>{{ obj.username }}</td>
        <td>{{ obj.username }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
  <div class="w-100 p-3 container py-5shadow-sm p-3 mb-5 bg-light rounded" style="background-color: #eee;">
    {% for obj in page_obj %}
      Сегодня день рождения у:  <span >{{ obj.username }}</span>
    {% endfor %}
  </div>
  <div class="container-fluid">
    <p class="text-center">AS of {{ time }}</p>
  </div>
  <div class="card">
    <div class="card-body text-center bg-light">
      <p class="text-center">
        {{ cal |safe }}
      </p>
    </div>
  </div>
{% endblock %}

birthday/templates/includes/footer.html
     <p>© {{year}} Copyright <span style="color:red">B</span>irthday</p>  
      
      

birthday/templates/includes/header.html
{% load static %}   
<nav class="navbar navbar-light" style="background-color: #8B008B">
  <div class="container">
    <a class="navbar-brand" >
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">B</span>irthday</a>
    </a>
  </div>
</nav>      
 

birthday/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

birthday/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Зарегистрироваться
      </div>
      <div class="card-body">
        {% if form.errors %}
          {% for field in form %}
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}